# Generated by Django 3.0.8 on 2020-10-11 05:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Ámbito')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('sigla', models.CharField(blank=True, max_length=3, null=True, verbose_name='Sigla')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Número de Ámbito')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Funcionario', verbose_name='Encargado')),
            ],
            options={
                'verbose_name': 'Ámbito',
                'verbose_name_plural': 'Ámbitos',
                'ordering': ['numero'],
            },
        ),
    ]
