# Generated by Django 3.0.8 on 2020-10-11 05:57

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambitos', '0001_initial'),
        ('funcionarios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Caracteristica')),
                ('denominacion', ckeditor.fields.RichTextField(verbose_name='Denomiación')),
                ('tipo', models.CharField(blank=True, choices=[('OBLIGATORIA', 'OBLIGATORIA'), ('NO OBLIGATORIA', 'NO OBLIGATORIA')], max_length=15, null=True, verbose_name='Tipo de caracteristica')),
                ('numero', models.FloatField(verbose_name='Número de Característica')),
                ('fecha_actualizacion', models.DateField(default='2018-11-13', verbose_name='Fecha de última actualización')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('ambito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambitos.Ambito', verbose_name='Ámbito')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Funcionario', verbose_name='Encargado')),
            ],
            options={
                'verbose_name': 'Característica',
                'verbose_name_plural': 'Características',
                'ordering': ['ambito', 'numero'],
            },
        ),
    ]
