# Generated by Django 3.0.8 on 2020-10-11 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('caracteristicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristica',
            name='subrogante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caracteristica_subrogante', to='funcionarios.Funcionario', verbose_name='Subrogante'),
        ),
        migrations.AlterField(
            model_name='caracteristica',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caracteristica_funcionario', to='funcionarios.Funcionario', verbose_name='Encargado'),
        ),
    ]
