# Generated by Django 3.0.8 on 2020-10-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, verbose_name='Segundo apellido')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
        ),
    ]
